version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: medops-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: medicrm
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - medops-network

  redis:
    image: redis:7.2-alpine
    container_name: medops-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - medops-network

  app:
    build: .
    container_name: medops-app
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: dev
      MONGODB_HOST: mongodb
      REDIS_HOST: redis
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - redis
    networks:
      - medops-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mongodb_data:
  redis_data:

networks:
  medops-network:
    driver: bridge