spring:
  application:
    name: crm-user
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

server:
  port: 8080

secret:
  key: ${JWT_SECRET:userionowmiowe!@#niviwemci1238f9@SFSDFSiemiflsibisl!23gficfmbisoqofjioeF#isosdf-sfenioisemvie}
  expiration_hours: ${JWT_EXPIRATION_HOURS:1}