spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: true

    mongodb:
      uri: ${MONGODB_URI}

logging:
  level:
    org.springframework.security: INFO
    org.springframework.data.mongodb.core.MongoTemplate: INFO
    com.crm.adapter.out.persistence.mongodb: INFO
    root: WARN