spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

    mongodb:
      uri: ${MONGODB_URI}

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    com.crm.adapter.out.persistence.mongodb: DEBUG
    root: INFO

cors:
  allowed-origins: ${FRONTEND_URL:http://localhost:5173}